// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FooterMusic: typeof import('./src/components/item/FooterMusic.vue')['default']
    IconList: typeof import('./src/components/home/iconList.vue')['default']
    ItemMusicList: typeof import('./src/components/item/itemMusicList.vue')['default']
    ItemMusicTop: typeof import('./src/components/item/itemMusicTop.vue')['default']
    MusicDetail: typeof import('./src/components/item/MusicDetail.vue')['default']
    MusicList: typeof import('./src/components/home/musicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperTop: typeof import('./src/components/home/SwiperTop.vue')['default']
    TopNav: typeof import('./src/components/home/TopNav.vue')['default']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
